//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IconMasterXP.rc
//
#define IDC_SELECT                      3
#define IDCSHOWHELP                     4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_COLORSELECTION              104
#define IDR_MAINFRAME                   128
#define IDD_RESAMPLE                    130
#define IDD_ROTATE                      131
#define IDD_COLORIZE                    132
#define IDD_FORMATS                     133
#define IDS_INFO                        136
#define IDD_JPEG                        137
#define IDR_LVPOPUP                     138
#define IDD_PROGRESS                    140
#define IDD_CONSOLE                     141
#define IDD_PALETTE                     145
#define IDB_PATTBACK                    146
#define IDR_PNG1                        147
#define IDB_BANNER                      149
#define IDR_BANNER                      149
#define IDI_ICON1                       150
#define IDI_IMPORT                      150
#define IDI_DELETE                      151
#define IDI_EXPORT                      152
#define IDI_ICON4                       153
#define IDI_HELP                        153
#define IDI_MULTIPAGE                   154
#define IDI_RESAMPLE                    158
#define IDI_TRANSPARENT                 159
#define IDI_UNDO                        160
#define IDB_PNG1                        161
#define IDB_PAPER_ERROR                 161
#define IDB_PAPER                       162
#define IDB_PAPER_                      163
#define IDB_PAPER_INVALID               163
#define IDC_WIDTH                       1000
#define IDC_HEIGHT                      1001
#define IDC_WIDTHP                      1002
#define IDC_HEIGHTP                     1003
#define IDC_SIZES                       1004
#define IDC_ANTIALIAS                   1006
#define IDC_ANGLE                       1008
#define IDC_KEEPSIZE                    1009
#define IDC_HUE                         1011
#define IDC_COLOR                       1012
#define IDC_SAT                         1013
#define IDC_BLEND                       1014
#define IDC_ENCODERS                    1014
#define IDC_THEALAS                     1015
#define IDC_STAT                        1015
#define IDC_COMPRESSION                 1016
#define IDC_COMPRESSIONSTATUS           1017
#define IDC_PROGRESSIVE                 1018
#define IDC_OPTIMIZE                    1019
#define IDC_CREDITS                     1021
#define IDC_PROGRESS                    1022
#define IDC_OUT                         1023
#define IDC_IN                          1024
#define IDC_RATIO                       1026
#define IDC_SPLIT1                      1030
#define ID_FILE_TEST                    32771
#define ID_Menu                         32775
#define ID_EDIT_RESIZE                  32776
#define ID_EDIT_ZOOM                    32777
#define ID_ZOOM_1                       32778
#define ID_ZOOM_X2                      32779
#define ID_ZOOM_X3                      32780
#define ID_ZOOM_X4                      32781
#define ID_Menu32782                    32782
#define ID_Menu32783                    32783
#define ID_EDIT_BITDEPTH                32786
#define ID_FILTERS_THRESHOLD            32787
#define ID_FILTERS_COLORIZE             32788
#define ID_FILTERS_GAMMA                32789
#define ID_FILTERS_LIGHT                32790
#define ID_FILTERS_CONTRAST             32791
#define ID_FILTERS_SOFTEN               32792
#define ID_FILTERS_EDGE                 32793
#define ID_FILE_MULTI                   32801
#define ID_FILTERS_ALPHA                32802
#define ID_EDIT_TRANSPARENTCOLOR        32803
#define ID_TRANSPARENTCOLOR_PICKFROMIMAGE 32804
#define ID_TRANSPARENTCOLOR_WRITERGBVALUES 32805
#define ID_FILE_IMPORT                  32806
#define ID_FILE_EXPORT                  32807
#define ID_EDIT_MIRROR                  32808
#define ID_EDIT_FLIP                    32809
#define ID_BIT_4BIT                     32814
#define ID_BIT_8BIT                     32817
#define ID_BIT_2BIT                     32818
#define ID_BIT_32BIT                    32819
#define ID_Menu32820                    32820
#define ID_TRANSPARENTCOLOR_REMOVE      32821
#define ID_GAMMA_INCREASE               32824
#define ID_GAMMA_DECREASE               32825
#define ID_LIGHT_INCREASE               32826
#define ID_LIGHT_DECREASE               32827
#define ID_CONTRAST_INCREASE            32828
#define ID_CONTRAST_DECREASE            32829
#define ID_FILTERS_THRESHOLD_CHOOSER    32830
#define ID_EDIT_ROTATE                  32832
#define ID_EDIT_REMOVEITEM              32842
#define ID_BIT_24BIT                    32843
#define ID_THRESHOLD_INTERACTIVE        32845
#define ID_FILTERS_SHARPEN              32846
#define ID_FILTERS_NEGATIVE             32847
#define ID_EDIT_SELECTALL               32851
#define ID_BIT_TIPS                     32853
#define ID_THRESHOLD_TIPS               32854
#define ID_FILTERS_TIPS                 32855
#define ID_FILE_JPEGSETTINGS            32856
#define ID__D                           32857
#define ID__IMPORT                      32858
#define ID__EXPORT                      32859
#define ID__REMOVE                      32860
#define ID__RESAMPLE                    32861
#define ID_Menu32862                    32862
#define ID_Menu32863                    32863
#define ID_WITH_FILTERS                 32864
#define ID_EDIT_REVERT                  32865
#define ID_EDIT_REPLACECOLORS           32866
#define ID_EDIT_DUPLICATE               32867
#define ID_ZOOM_ENABLEANTI              32874
#define ID_VIEW_CONSOLE                 32876
#define ID_HELP_HOWTOBUYFULLVERSION     32877
#define ID_TRANSPARENTCOLOR_HELP        32878
#define ID_THRESHOLD_HELP               32879
#define ID_EDIT_PALETTE                 32882
#define ID_VIEW_BACKGROUND              32883
#define ID_BACKGROUND_PATTERN           32884
#define ID_BACKGROUND_COLOR             32885
#define ID_BACKGROUND_EDITCOLOR         32886
#define ID_FILE_DON                     32887

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32890
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
